# This file is auto-generated by goreleaser on each release.
# Do not edit by hand.
class Awscost < Formula
  desc "Terminal UI for exploring AWS costs"
  homepage "https://github.com/OuFinx/awscost"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/OuFinx/awscost/releases/download/v0.0.0/awscost_0.0.0_darwin_arm64.tar.gz"
      sha256 "placeholder"
    end
    on_intel do
      url "https://github.com/OuFinx/awscost/releases/download/v0.0.0/awscost_0.0.0_darwin_amd64.tar.gz"
      sha256 "placeholder"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/OuFinx/awscost/releases/download/v0.0.0/awscost_0.0.0_linux_arm64.tar.gz"
      sha256 "placeholder"
    end
    on_intel do
      url "https://github.com/OuFinx/awscost/releases/download/v0.0.0/awscost_0.0.0_linux_amd64.tar.gz"
      sha256 "placeholder"
    end
  end

  def install
    bin.install "awscost"
  end

  test do
    system "#{bin}/awscost", "-version"
  end
end
