# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3lo < Formula
  desc "Use AWS S3 as a container image registry"
  homepage "https://github.com/OuFinx/s3lo"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OuFinx/s3lo/releases/download/v0.0.1/s3lo_darwin_amd64.tar.gz"
      sha256 "d6aab3e5f96758f0d536c823cb04b69271b10746a324c00e03260ea177ec16d8"

      define_method(:install) do
        bin.install "s3lo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OuFinx/s3lo/releases/download/v0.0.1/s3lo_darwin_arm64.tar.gz"
      sha256 "61cb45cefd0c9cc320246be6978798f29fcc543e8f01f6482fd7262d22cfdf8f"

      define_method(:install) do
        bin.install "s3lo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OuFinx/s3lo/releases/download/v0.0.1/s3lo_linux_amd64.tar.gz"
      sha256 "3430233b46d41f8c9974887c8726aa0e2c854f7875eb13dd80db9a22f13fafd6"
      define_method(:install) do
        bin.install "s3lo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OuFinx/s3lo/releases/download/v0.0.1/s3lo_linux_arm64.tar.gz"
      sha256 "63ef97765504aba9e854195b37752efff84355dc02a10e52d08ae69490cf41ac"
      define_method(:install) do
        bin.install "s3lo"
      end
    end
  end

  test do
    system "#{bin}/s3lo", "version"
  end
end
