# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3lo < Formula
  desc "Use AWS S3 as a container image registry"
  homepage "https://github.com/OuFinx/s3lo"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OuFinx/s3lo/releases/download/v1.14.0/s3lo_darwin_amd64.tar.gz"
      sha256 "53c4d65d4921ccff716b4fd0b421d32b50095233a3d969fef441ccf1eca869a6"

      define_method(:install) do
        bin.install "s3lo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OuFinx/s3lo/releases/download/v1.14.0/s3lo_darwin_arm64.tar.gz"
      sha256 "1a1fb21daac00112b87292253cd5606617dea77e438524acb08418441e577bb6"

      define_method(:install) do
        bin.install "s3lo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OuFinx/s3lo/releases/download/v1.14.0/s3lo_linux_amd64.tar.gz"
      sha256 "a65844e33bb43e67349c57e78ba783034329f8d4f3642c8f9c86c03325e02046"
      define_method(:install) do
        bin.install "s3lo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OuFinx/s3lo/releases/download/v1.14.0/s3lo_linux_arm64.tar.gz"
      sha256 "895505c8733d3ad29f611d048812e31ef8d5eb2ecfe7fc7c88e21db5474fae65"
      define_method(:install) do
        bin.install "s3lo"
      end
    end
  end

  test do
    system "#{bin}/s3lo", "version"
  end
end
